### ISSUE TITLE
Create the Parameter Store Parameters

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#129]
Per #113 we'll need SSM Parameters for all the 2018 API containers:
- [x] disaster-resilience
- [x] housing-affordability
- [x] local-elections
- [x] neighborhood-development
- [x] transportation-systems

**Comment by MikeTheCanuck** [comment]
## ToDo
- [ ] verify the POSTGRES_PASSWORD values that I have already placed there
- [ ] insert the appropriate DJANGO_SECRET_KEY values (encrypted)
- [ ] get a finalized **transportation-systems** database name (POSTGRES_NAME)
- [ ] add these values to my spreadsheet, save as CSV, upload to devops bucket
