### ISSUE TITLE
DNS updates - checklist

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#194]
There's a lot of DNS changes that need to be made to keep up with the changes we've made and need to make to our infrastructure.

While those changes are for the most part already specified in other issues as a final step once the changes have been completed, it wouldn't hurt to keep a central list of those changes so we can see the net effect - and have consistent governance/branding - of the assets under HackOregon.

## A Records to edit/redirect
1. [ ] civicpdx.org - #186 
2. [ ] 2017.civicpdx.org - will this be redirected to 2017.civicplatform.org?
3. [ ] budget.civicpdx.org - #192 
4. [ ] emergency-response.civicpdx.org - #192 
5. [ ] homelessness.civicpdx.org - #192 
6. [ ] housing.civicpdx.org - #192 
7. [ ] service.civicpdx.org - #185 
8. [ ] transportation.civicpdx.org - #192 
9. [ ] www.civicpdx.org - will this be redirected to civicplatform.org?

## A Records to introduce
10. [ ] civicpdx.com - #187 
11. [ ] www.civicplatform.org - like (9) above - or are we graduating past this convention now?

## A Records to delete(?)
12. [ ] staging-2018.civicpdx.org - this can safely be deleted, yes?

## CNAME Records to manage(?)
13. [ ] _cb1858cb4845a5bd6299c366697a1ec0.service.civicpdx.org - [Issue 148](https://github.com/hackoregon/civic-devops/issues/148#issuecomment-395982161) shows when this was created, but I'm not sure if it's safe to delete this per #171 - or if it (or something like it) will be necessary when the cert gets renewed
14. [ ] _af29dd9bbcad31f1897b0d48657c7e3a.sandbox.civicpdx.org - similarly, per #171, not sure if this needs to be preserved

**Comment by jaronheard** [comment]
Just going to throw in my two cents on www.civicplatform.org -- I'd like to identify this record to add as higher priority, as people may add the www without thinking about it and have a bad time.

**Comment by jaronheard** [comment]
Can we make sure that www.civicplatform.org gets added?

<img width="716" alt="image" src="https://user-images.githubusercontent.com/7065695/61419520-72ca8c80-a8b3-11e9-9609-422fe50fd513.png">
