### ISSUE TITLE
Initial IAM automation

### ISSUE THREAD

**Issue by danieldn** [hackoregon/civic-devops#225]
Instructions: Replace text below with details corresponding to your story

**Summary**

As an infra team, we want IAM roles and groups and policy to be defined as code.

**Impact**

T1

**Tasks**
- [ ] ID accounts and groups that are outdated, create a list of said accounts, and send to admin (i.e. ML)
- [ ] ID accounts that do not follow our new naming conventions (ML wanted FirstnameLastname for IAM)
- [ ] Begin a template for automating current users (i.e. CF or AWSLabs something available)

**Definition of Done**

- IAM should reflect only current active users for 2019 hacko season
- Admin should be able to run a CF template or solution that adds some users (limit this to only existing before attempting to import all developers)
- Added users should have programmatic access but not console
- Documentation on how to run solution and the expected outcome
