### ISSUE TITLE
Request: Hosting static site for education

### ISSUE THREAD

**Issue by danieldn** [hackoregon/civic-devops#231]
Instructions: Replace text below with details corresponding to your story

**Summary**

https://docs.google.com/document/d/1d3T4VqD2Hy0A-XtGJUM-DTKj0V25nGVGLOfcQhwPp-I/edit

**Impact**

**Tasks**
- [ ] Get Github and AWS access for Vinny
- [ ] ID who needs on team education for AWS
- [ ] Setup new S3 bucket with correct permissions 
- [ ] TODO

**Definition of Done**

Team education successfully hosts their static site at the mentioned domain. Document how this fits into current build process (Travis).

**Comment by VMannello** [comment]
Some updates on this process:
 - I have github and AWS access!
 - This platform request will serve as the request to document how to standup an s3 static site over cloudfront with https
 - We decided no one on the edu team will need AWS access as TravisCL will be the one putting the build file on s3
 - TravisCL will use the IAM user s3-static-deploy to deploy a static site.
 - CloudFormation template is done and lives at https://github.com/hackoregon/hackoregon-aws-infrastructure/blob/master/infrastructure/s3-static-https.yaml
 
**New Tasks**
- [ ] Build basic gatsby project and configure travis file for static-site boilerplate 
- [ ] Acquire SSL Certificate, import to ACM and get its ARN
- [ ] Use CloudFormation template to stand up bucket with connected cert
- [ ] Test travis deploy

**Comment by VMannello** [comment]
Gatsby Default Starter for Hack Oregon projects has been created at: https://github.com/hackoregon/gatsby-starter-default

When setting up travis for a static deployment the appropriate repository will need to have these variables:
AWS_ACCESS_KEY_ID: Access key of IAM site deployer (should match what was used in CloudFormation)
AWS_SECRET_ACCESS_KEY: Secret Key for user
AWS_DEPLOY_BUCKET: Bucket name to deploy files to (can be found in CloudFormation output)
SITE_HOSTNAME: Full site address (with protocol) bash escaped e.g. https:\/\/project.hackoregon.org
