### ISSUE TITLE
Request: Sandbox RDS Instance

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#237]
**Summary**

Sandbox team wants their RDS instance

**Notes**

Lynn talked to me (Mike Lonergan) on 2019-05-19 at Centrl and I got a clear picture that they're on deck next, so I'm queuing this ahead of the Google Doc access form that Lynn'll submit soon.

**Tasks**
- [ ] Manual RDS installation
- [ ] Manual account creation
- [ ] Manual `postgis` addition
- [ ] communicate PEM file, creds, connection params and pointer to the "how to use jumpbox for RDS installs" HOWTO guide to Lynn

**Definition of Done**

Lynn's got the necessary bits above to hand off to the team's PostgreSQL admin.

**Comment by MikeTheCanuck** [comment]
Here's what will be manually installed:

DB instance identifier: sandbox-2019-staging
Use case: dev/test (non-replicated)
DB engine: PostgreSQL 11.2-R1
DB instance class: db.t2.small
Allocated storage: 60GB (Lynn believes they have 52 GB of data now)
VPC: public-database
VPC security groups: hacko-public-database
log exports: Postgresql logs published to CloudWatch
Enable deletion protection
All other settings at default.

**Comment by MikeTheCanuck** [comment]
Server address: 

Instructions for how to use jumpbox for PostgreSQL restore:
https://github.com/hackoregon/civic-devops/blob/master/docs/database/2019/HOWTO:%20Use%20jumpbox%20to%20restore%20PostgreSQL%20from%20S3.md

PEM file, username and password will be distributed via Slack DM.

NOTE: the #236 step has to be manually taken after database is installed, to make `postgis` available to the database.

**Comment by MikeTheCanuck** [comment]
Post-creation configuration steps:

- create application login role via PgAdmin
- add PostGIS support to all future databases via https://github.com/hackoregon/civic-devops/issues/236#issuecomment-493790287

**Comment by MikeTheCanuck** [comment]
creds & connectivity details shared with @nam20485 via Slack.

**Comment by nam20485** [comment]
Thanks Mike, I was able to connect using the settings you provided.
