### ISSUE TITLE
Refactor hard-coded FQDN's in CloudFormation templates

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#240]
**Summary**

With #239, we'll need the ability to substitute a different `Host` value in one place in the master template for each of staging and production (and any test environments we create).  Until then, I'll be chasing down all the various instances of the predictable strings in hard-to-reach places.

**Impact**

Impacts S5.

**Tasks**
- [ ] Decide on naming convention for staging URLs
- [ ] Instantiate DNS records for staging domains
- [ ] Create the variable, declare their values, substitute for the various `Host` values scattered throughout

**Definition of Done**

Test environments can be deployed with the new parameterized `Host` values.

**Comment by MikeTheCanuck** [comment]
The `Host` values to be managed:
- service.civicpdx.org - domain for all API containers
- 2017.civicpdx.org/ civicpdx.org - domains for the container hosting the React applications from the 2017 project season
- civicplatform.org - domain for the container hosting the React applications from the 2018 project season
