### ISSUE TITLE
Add SSM parameters for 2019 projects

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/civic-devops#242]
**Summary**

Generate and upload the SSM parameters to support 2019 projects.

**Impact**

Impacts S2, S3, S4, S5

**Tasks**
- [ ] Determine the parameters (environment variables) needed for each 2019 project - get them documented here: https://docs.google.com/spreadsheets/d/1rTkjqcVEul-oXvIVJ8GseYpMTYc5AqdW2MV3KisHnpM/
- [ ] Upload them to the /staging/2019/[project_name]/ namespace
- [ ] Extend the IAM role to grant access to the new /staging/2019 and /production/2019 namespaces https://github.com/hackoregon/civic-devops/issues/114

**Definition of Done**

Parameter values are readable by the first-deployed 2019 API service.

**Comment by nam20485** [comment]
Minimum set of SSM parameters needed to deploy 2019 backend via travis:

https://travis-ci.org/hackoregon/2019-sandbox-backend/settings
