### ISSUE TITLE
Create a new frontend service for the OMSI disaster game

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic-devops#277]
**Summary**

Create a new frontend service for the OMSI disaster game.

**Impact**

This is in service of the 2019 disaster team. The impact is a new service running in ECS and a new path in the load balancer.

For now, this is strictly for demo purposes to quickly share work with the OMSI team. For "production" we expect to host the game on the local machine in the OMSI installation.

**Tasks**
- [ ] Create an ECR repo
- [ ] Extend the master.yaml file to include a new `fargate-frontend` service.
- [ ] Wire up continuous deployment in the civic repo's travis environment.

**Definition of Done**

Our frontend team is able to merge code to master on the Civic repo and cause deployments of the OMSI disaster game.
