### ISSUE TITLE
Cost analysis on Fargate vs. EC2 backing for ECS

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hackoregon/civic-devops#77]
[AWS Fargate](https://aws.amazon.com/fargate/) is now available in our region. It eliminates the need to allocate EC2 machines for our tasks, instead dynamically scaling compute power with the services registered.

This would be amazing to have, since it's one less thing to deal with, but before pulling the trigger, we should run the numbers.

**TODO:**
  - [ ] Get the cost/mo for end of 2018, (i.e., 2017 APIs, 2018 APIs, both web frontends) using EC2 + ECS pricing
  - [ ] Get the cost/mo for end of 2018 using Fargate + ECS pricing
  - [ ] Share the figures in this issue

Based on the results of this analysis, we'll determine if it's worth migrating. 

We can address the question of how much work the migration will be and when to do the migration only if conclude that the move makes sense fiscally.

**Comment by iant01** [comment]
Cost for container repository (ecr) and data transfer in/out from containers is the same for ecs ec2 and ecs fargate so those tiems are a wash. Currently the two T2large (2 cpu and 8 GB memory each) container instances are costing roughly $133.00 a month excluding ecr and data transfer costs. This cost is regardless of what use/load is occuring (currently very little use over past six months) roughly 50% of the available memmory is pre-allocated.

For fargate the cost for an equivalent amount of cpu and memory would be roughly $144.00 per month if there were sufficient load to use the full reserved cpu and memory (again excluding the cost of ecr and data transfer which would be the same between fargate and ec2 for the same load). At current monthly load, fargate is less expensive.

To move to fargate, we would need to change the network setup and would have to define the load balancer target rules (fargate does not do that automagically as ecs/ec2 does. Would also need to better define the cpu and memory needs for each container so as to not wildly ofer reserve but also have enough for the container to run properly this setting has more of an effect in a fargate setup than an ec2 setup.

I will be loking into more detail on what changes would be needed in the configuration setup to be able to move to a fargate setup and document those items.
